CREATE TABLE customer(
    id BIGSERIAL PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL,
    age INT NOT NULL,
    gender TEXT NOT NULL,
    role TEXT NOT NULL,
    CREATED_USER TEXT NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_USER TEXT,
    UPDATED_AT TIMESTAMP
);

CREATE TABLE product(
    id BIGSERIAL PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT NOT NULL,
    weight INTEGER NOT NULL,
    height FLOAT NOT NULL,
    width FLOAT NOT NULL,
    quantity INTEGER NOT NULL,
    price FLOAT NOT NULL,
    customer_id BIGSERIAL NOT NULL,
    CREATED_USER TEXT NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_USER TEXT,
    UPDATED_AT TIMESTAMP
);