CREATE TABLE customer(
    id BIGSERIAL PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL,
    age INT NOT NULL,
    gender TEXT NOT NULL,
    role TEXT NOT NULL,
    CREATED_USER TEXT NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_USER TEXT,
    UPDATED_AT TIMESTAMP
);