CREATE TABLE address(
    id BIGSERIAL PRIMARY KEY,
    house_number INTEGER NOT NULL,
    city TEXT NOT NULL,
    county INTEGER NOT NULL,
    zip_code FLOAT NOT NULL,
    customer_id BIGSERIAL NOT NULL,
    CREATED_USER TEXT NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_USER TEXT,
    UPDATED_AT TIMESTAMP
);