CREATE TABLE order_table(
    id BIGSERIAL PRIMARY KEY,
    total_price FLOAT NOT NULL,
    CREATED_USER TEXT NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_USER TEXT,
    UPDATED_AT TIMESTAMP
);